[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OEG SDK for Android"
authors = [{name = "Justin", email = "congtuyenvip@gmail.com"}]
dynamic = ["version", "description"]
